### ISSUE TITLE
Error with profile block

### ISSUE THREAD

**Issue by emanuele45** [SimplePortal/SimplePortal_ElkArte#20]
Enabling the profile block seems to lead to the following error:
```
Tipo di errore: Generale
Warning: in_array() expects parameter 2 to be array, null given
http://dominio.it/index.php?
File:  ... sources/Load.php
Riga: 978
```
I'm not yet sure if it is a bug in SP or in ElkArte.
In both cases, it seems the issue is that loadMemberData is called too early, before $context['admin_features'] is populated.

**Comment by Spuds** [comment]
closing as inactive
