### ISSUE TITLE
Forum not visible on iOS

### ISSUE THREAD

**Issue by radu81** [SimplePortal/SimplePortal_ElkArte#25]
A few users on my forum just reported that the forum is not visible on ios. I did a quick test with Safari and Chrome on an old iPhone 5 and indeed the forum is not displayed if the portal is enabled. If portal is disabled the forum is disabled correctly. I didn't see this problem on Chrome or Firefox for Android.

I attach a screenshot I just received
https://www.skodaclub.it/index.php?action=dlattach;topic=11357.0;attach=43080;image

**Comment by Spuds** [comment]
Any debug information on the iPhone browser console?

**Comment by radu81** [comment]
Debug without a MAC it's not an easy task, or at least not for me. Strange is I found another forum based on the same version of elkarte and sp which runs fine on iPhone.

In a test forum I removed all add-ons, I removed my custom css file, I removed all blocks and profiles and created just a couple of blocks but nothing changed.

**Comment by Spuds** [comment]
> Debug without a MAC it's not an easy task, 

Tell me about it !
And just to verify its only iOS that has the issue ... its not a overall mobile issue, but a specific iOS mobile problem.

**Comment by Spuds** [comment]
Looking here: https://caniuse.com/#feat=flexbox

I wonder if its a flexbox issue ... looks like iOS did not fully support this until iOS 9 .... I don't know what versions of iOS run on different phones though.  We can improve support with the -webkit  prefix

**Comment by radu81** [comment]
one member reported this on iOS 10.3.3. I made a test with an iPhone 5 which cannot be updated to iOS 11, so it's a 10.x version. I think is related to iOS and not to Safari, I tested both Chrome and Safari and both are having the same problem.

**Comment by radu81** [comment]
With ios 11 the forum is displayed correctly

**Comment by Spuds** [comment]
And it shows on a desktop Mac running 10.12 w/Safari 10 .... so something to do with iOS ... something.

**Comment by Spuds** [comment]
Going to close this as "old" ... it might have been a flexbox issue, or simply a portal disabling itself for a detected mobile device ... who knows.  I've been working on some rc2 updates so lets start fresh there.
