### ISSUE TITLE
Getting a hack warning

### ISSUE THREAD

**Issue by AutomationMan808** [SimplePortal/SimplePortal_ElkArte#53]
Fatal error: Uncaught Elk_Exception: Hacking attempt... in /Db-mysql.class.php(163): Database_Abstract->error_backtrace('Hacking attempt...', 'Illegal charact...', true, '/home3/financia...', 534) #1 Db-abstract.class.php on line 404

**Comment by Spuds** [comment]
That is most likely an issue of running an older version of SP with ElkArte 1.1.9.  Do you know what version of SP you are running?

You will need to edit your `Portal.subs.php` file and find the line that says

```
'query' => empty($allowed) ? '0=1' : 'FIND_IN_SET(%s, \'' . implode(',', $allowed) . '\')',
```
and change that to
```
'query' => empty($allowed) ? '0=1' : 'FIND_IN_SET(%s, "' . implode(',', $allowed) . '")',
```

**Comment by AutomationMan808** [comment]
It's the one that was in the package manager

**Comment by Spuds** [comment]
I'll update the one via package manager, its pointing to the old file
