### ISSUE TITLE
Quick search referring to action=search2

### ISSUE THREAD

**Issue by emanuele45** [SimplePortal/SimplePortal_ElkArte#6]
The URL should be changed to `action=search;sa=results` instead. :angel: 
xref: http://www.italiansmf.net/forum/index.php?topic=2146.0

**Comment by Spuds** [comment]
https://github.com/SimplePortal/SimplePortal_ElkArte/commit/1fea4ad499e0a921b24325b5198f5b901545c6f4#diff-742871347d368766f11eeaa7116bc893
