### ISSUE TITLE
Disable blocks parameter

### ISSUE THREAD

**Issue by emanuele45** [SimplePortal/SimplePortal_ElkArte#7]
Reading this support request http://simpleportal.net/index.php?topic=14410.0 I had the idea that it would be potentially useful sometimes (especially in case of html and php blocks) an URL parameter that completely disables any block, a sort of "safe mode" to allow to access the admin panel even if "someone" screwed up very bad something.

**Comment by silentguardian** [comment]
I think I had already mentioned how you could do this with SimplePortal:

http://www.elkarte.net/community/index.php?topic=1399.msg12902#msg12902

**Comment by Spuds** [comment]
Just tested to be sure and adding ?debug to the url still turns off the portal.   So closing this as "holy crap its 5 years old."
